---
title: "Trees"
author: "Samuel Aroney"
date: "`r format(Sys.time(), '%d %B %Y')`"
output:
  bookdown::pdf_document2:
    toc: FALSE
  bookdown::html_document2: default
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE, error = FALSE, fig.width = 6, fig.asp = 0.618, out.width = "100%", fig.align = "center")

library(tidytree)
library(ggtree)
library(cowplot)
library(tidyverse)
library(here)
#source(here("setup.R"))

map <- purrr::map
main_dir <- here("GraftM-analysis", "output")
dir.create(main_dir, recursive = TRUE)

colour_brewer <- setNames(append(as.list(RColorBrewer::brewer.pal(12, "Paired")), c("#737373", "#FFFFFF", "#000000")), c("blue", "darkblue", "green", "darkgreen", "red", "darkred", "orange", "darkorange", "purple", "darkpurple", "yellow", "brown", "grey", "white", "black"))
habitat_levels <- c("Palsa", "Bog", "Fen")
colour_habitat <- c("#703C1B", "#058000", "#0001FF")
shape_habitat  <- c(15, 16, 17)
fill_habitat   <- colour_habitat

depth_levels <- c("0-9", "10-19", "20-29", "30-39")
depth_labels <- c("0", "10", "20", "30")
fill_depth   <- RColorBrewer::brewer.pal(5, "YlOrBr")[-1]
colour_depth <- fill_depth

year_levels <- c("2011", "2012", "2013", "2014", "2015", "2016", "2017")
year_labels <- year_levels
fill_year   <- RColorBrewer::brewer.pal(7, "OrRd")
colour_year <- fill_year

set.seed(42)
```

```{r wrangling}

map_chr( c("all_aab_dh"), ~ here("GraftM-analysis/output", ., str_c(., ".gpkg"), str_c(., "_draft.gpkg.refpkg"), str_c(., ".tre"))
        
trees <- tibble(gene = c("all_aab_dh")) %>%
  mutate(
    tree_path = map_chr(gene, ~ here("GraftM-analysis/output", ., str_c(., ".gpkg"), str_c(., "_draft.gpkg.refpkg"), str_c(., ".tre"))),
    tree = map(tree_path, read.tree),
    tax_path = map_chr(gene, ~ here("GraftM-analysis/output", ., str_c(., "_tax.tsv"))),
  )
```

```{r spec-summary-function}
plot_tree <- function(tree, filename) {
  tree %>%
    ggtree()
    # geom_tiplab(aes(subset = label == "characterised"), label = "characterised")
  ggsave(here(main_dir, filename), width = 12, height = 7, dpi = 900)
}
```

```{r spec-summary}
plot_tree()
```